[package]
name = "k2node-to-json"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
anyhow = "1.0.51"
uuid = { version = "0.8", features = ["v4"] }
strum = { version = "0.23.0", features = ["derive"] }
strum_macros = "0.23.0"
csv = "1.1"
